### PR TITLE
Dockerized our server and can be pushed onto AWS

### PR DESCRIPTION
**Pull request by ss-jiang**
Our server works on AWS and runs if you connect to the URL addresses in the readme.

### CODE REVIEW

**Comment by kevin-xr-wu** [comment]
Awesome!! I can access it from my own machine!!!!

**Comment by rishub** [comment]
me too!!

**Comment by rishub** [comment]
hmm travis failed though

**Comment by ss-jiang** [comment]
Seems like travis isnt happy :(

**Comment by ss-jiang** [comment]
Travis v happi now :)

**Comment by rishub** [comment]
niceee

**Pull request merged**
